name: Schedule workflow

on:
  schedule:
      - cron: "0 0 *  *  *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Schedule workflow is done"
